import fs from "node:fs";
import path from "node:path";

const MAX_LENGTH = 6;
const MIN_LENGTH = 4;

const response = await fetch("https://gist.githubusercontent.com/pikapower9080/749c8b7bb43ea38f6b02c0a84f016616/raw/12of12inf.txt");
const data = await response.text();
const words: string[] = data.split("\n");

let filteredWords = words.filter((word:string) => word.length >= MIN_LENGTH && word.length <= MAX_LENGTH && /^[a-zA-Z]+$/.test(word));

filteredWords = filteredWords.sort();

const header = `// http://wordlist.aspell.net/12dicts/
// ${filteredWords.length.toLocaleString()} words between ${MIN_LENGTH} and ${MAX_LENGTH} letters
// Generated by scripts/generate_word_list.ts - do not edit manually`
fs.writeFileSync(path.resolve("src", "lib", "words.ts"), `${header}\n\nexport const words = ${JSON.stringify(filteredWords)};\n`);
console.log(`wrote ${filteredWords.length.toLocaleString()} words`);
